FROM ghcr.io/cirruslabs/flutter:stable
WORKDIR /app
COPY pubspec*.yaml ./
RUN flutter pub get
COPY . .
EXPOSE 8080
CMD ["flutter", "run", "-d", "web-server", "--web-port=8080", "--web-hostname=0.0.0.0", "--dart-define-from-file=config/dev.json"]
